/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Worker } from "./Worker";
import { WorkerCountArgs } from "./WorkerCountArgs";
import { WorkerFindManyArgs } from "./WorkerFindManyArgs";
import { WorkerFindUniqueArgs } from "./WorkerFindUniqueArgs";
import { CreateWorkerArgs } from "./CreateWorkerArgs";
import { UpdateWorkerArgs } from "./UpdateWorkerArgs";
import { DeleteWorkerArgs } from "./DeleteWorkerArgs";
import { WorkerService } from "../worker.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Worker)
export class WorkerResolverBase {
  constructor(
    protected readonly service: WorkerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Worker",
    action: "read",
    possession: "any",
  })
  async _workersMeta(
    @graphql.Args() args: WorkerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Worker])
  @nestAccessControl.UseRoles({
    resource: "Worker",
    action: "read",
    possession: "any",
  })
  async workers(@graphql.Args() args: WorkerFindManyArgs): Promise<Worker[]> {
    return this.service.workers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Worker, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Worker",
    action: "read",
    possession: "own",
  })
  async worker(
    @graphql.Args() args: WorkerFindUniqueArgs
  ): Promise<Worker | null> {
    const result = await this.service.worker(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Worker)
  @nestAccessControl.UseRoles({
    resource: "Worker",
    action: "create",
    possession: "any",
  })
  async createWorker(@graphql.Args() args: CreateWorkerArgs): Promise<Worker> {
    return await this.service.createWorker({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Worker)
  @nestAccessControl.UseRoles({
    resource: "Worker",
    action: "update",
    possession: "any",
  })
  async updateWorker(
    @graphql.Args() args: UpdateWorkerArgs
  ): Promise<Worker | null> {
    try {
      return await this.service.updateWorker({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Worker)
  @nestAccessControl.UseRoles({
    resource: "Worker",
    action: "delete",
    possession: "any",
  })
  async deleteWorker(
    @graphql.Args() args: DeleteWorkerArgs
  ): Promise<Worker | null> {
    try {
      return await this.service.deleteWorker(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
